# Generated by Django 2.1 on 2018-08-10 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pitanje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=300)),
                ('tekst_pitanja', models.CharField(max_length=2000)),
                ('ime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Osoba')),
            ],
        ),
    ]
